zixuan97/algotech-be

prisma/migrations/20220903050058_/migration.sql
prisma/schema.prisma
public/controllers/userController.js
public/models/userModel.js
public/routes/userRoutes.js

- CRUD for user
- Enable/ disable user
- Change user roles
- TODO: Forget password, logout

Feat: Common Infrastructure

---

index.js
prisma/migrations/20220903154604_added/migration.sql
prisma/migrations/20220904135525_added/migration.sql
prisma/schema.prisma
public/controllers/categoryController.js
public/controllers/userController.js
public/helpers/error.js
public/models/categoryModel.js
public/models/userModel.js
public/routes/categoryRoutes.js

Fix user auth 
Added category routes

feat(category) : category routes and methods

---

package-lock.json
package.json
prisma/migrations/20220903050058_/migration.sql
prisma/schema.prisma
public/controllers/userController.js
public/models/userModel.js
public/routes/userRoutes.js

AT-86: Common Infrastructure Backend

---

public/controllers/userController.js

test: changing of userController `url` to include 'https'

userController auth testing

---

public/controllers/userController.js

quick fix (2), test .domainName.com

Auth cookie fix (2)

---

public/controllers/userController.js

fix: change route for domain to include `/`

Auth cookie fix (3)

---

public/controllers/userController.js

Auth cookie fix(4)

---

public/controllers/userController.js

Removing httpOnly

---

index.js

Trying origin: true

---

index.js

fix: include method:'GET,HEAD,PUT,PATCH,POST,DELETE'

defining methods, remove origin:true

---

index.js

Set trust proxy as 1

---

public/controllers/userController.js

Revert changes back to norm

---

customers.txt
package-lock.json
package.json
prisma/migrations/20220911144745_/migration.sql
prisma/schema.prisma
public/controllers/userController.js
public/helpers/email.js
public/models/userModel.js

- Added both email methods (with and without attachments)
- Split user into first name and last name
- Changed create method to add first name, last name and role

Fix: Added first name and last name attribute to user

---

public/controllers/productController.js
public/helpers/s3.js
public/models/productModel.js

AT-92: create and update product api routes

---

customers.txt
prisma/schema.prisma
public/controllers/procurementController.js
public/helpers/email.js
public/helpers/pdf.js
public/models/procurementModel.js
public/models/productModel.js
public/routes/procurementRoutes.js

- Attach purchase order PDF and send as attachment in email
- Replace hardcoded PDF variables with input variables
- Implement procurement order total amount logic in backend

AT-94: Procurement Backend

---

public/controllers/userController.js
public/helpers/email.js
public/models/userModel.js

- Generate a password for new user

Fix: Generate password upon creation of new user

---

public/controllers/userController.js

fix: change `const` to `let` for user attribute, fix error throwing

fix: userController::editUser fixes

---

prisma/schema.prisma
public/controllers/procurementController.js
public/models/procurementModel.js
public/models/stockQuantityModel.js

- Return PO object for create and update method
Example of return object:
- Added stockQuantityModel
- Changed productCategory to category

Fix: Procurement order methods

---

public/controllers/bundleController.js
public/controllers/locationController.js
public/models/bundleModel.js
public/models/locationModel.js

Updated bundle controller and location methods

feat: bundle updates

---

index.js
prisma/migrations/20220923071028_updated_sales_order_fields/migration.sql
prisma/migrations/20220923072421_optional_remarks_for_customer_orders/migration.sql
prisma/migrations/20220923163439_update_nullable_for_salesorder/migration.sql
prisma/schema.prisma
public/controllers/procurementController.js
public/controllers/salesOrderController.js
public/controllers/shopeeController.js
public/controllers/shopifyController.js
public/helpers/shopeeApi.js
public/helpers/shopifyApi.js
public/models/salesOrderModel.js
public/routes/salesRoutes.js

Get revenue by day based on time filter
Get orders by day based on time filter
Get all orders based on time filter
CRUD functionalities

Feat: SalesOrder Controller methods

---

index.js
package-lock.json
package.json
public/controllers/lazadaController.js
public/controllers/salesOrderController.js
public/controllers/shopeeController.js
public/helpers/lazadaApi.js
public/helpers/shopeeApi.js
public/models/salesOrderModel.js
public/routes/lazadaRoutes.js
public/routes/salesRoutes.js

TODO: multiple order items with same name (have to fix)

feat: added and connected lazada apis

---

prisma/migrations/20220928013152_add_user_to_deliveryorder/migration.sql
prisma/schema.prisma
public/controllers/deliveryController.js
public/controllers/supplierController.js
public/models/deliveryModel.js
public/models/supplierModel.js
public/routes/deliveryRoutes.js
public/routes/supplierRoutes.js

- Associate supplier with product
- Associate delivery order with user

Fixes: Sync up Delivery Order with FE

---

public/controllers/salesOrderController.js
public/routes/salesRoutes.js

GET request shouldn't have request body

change get sales by order id to read orderId from params instead of req body

---

package-lock.json
package.json
public/controllers/userController.js
public/models/context.js
public/tests/brand.test.js
public/tests/brandModel.test.js
public/tests/bulkOrder.test.js
public/tests/user.test.js

model still testing and trying out

feat: jest unit testing

---

.github/workflows/cron.yaml
.github/workflows/tokens.yaml

refactor: Uncommmented out cron job

Merge main into branch
